import { AnalysisResult } from '../engine';

export async function exportReport(results: AnalysisResult, format: 'txt' | 'json' | 'html'): Promise<string> {
  console.log(`Exporting report in ${format} format`);
  
  switch (format) {
    case 'txt':
      return exportTxtReport(results);
    case 'json':
      return exportJsonReport(results);
    case 'html':
      return exportHtmlReport(results);
    default:
      throw new Error(`Unsupported format: ${format}`);
  }
}

function exportTxtReport(results: AnalysisResult): string {
  let report = '';
  report += 'KNOUX Project Intelligence Desktop™ - Analysis Report\n';
  report += '='.repeat(60) + '\n\n';
  
  // Project Summary
  report += 'PROJECT SUMMARY\n';
  report += '-------------\n';
  report += `Name: ${results.projectSummary.name}\n`;
  report += `Type: ${results.projectSummary.type}\n`;
  report += `Size: ${formatFileSize(results.projectSummary.size)}\n`;
  report += `Score: ${results.projectSummary.score}%\n\n`;
  
  // Detected Stack
  report += 'DETECTED TECHNOLOGY STACK\n';
  report += '------------------------\n';
  report += `${results.detectedStack.join(', ') || 'None detected'}\n\n`;
  
  // Progress Summary
  report += 'PROGRESS SUMMARY\n';
  report += '---------------\n';
  report += `Overall Score: ${results.progressData.overallScore}%\n`;
  report += `Files: ${results.progressData.fileProgress.total} total, `;
  report += `${results.progressData.fileProgress.ready} ready, `;
  report += `${results.progressData.fileProgress.partial} partial, `;
  report += `${results.progressData.fileProgress.stub} stubs\n\n`;
  
  // Critical Files
  report += 'CRITICAL FILES TO ADDRESS\n';
  report += '------------------------\n';
  if (results.roadmap.criticalFiles.length > 0) {
    results.roadmap.criticalFiles.forEach((file, i) => {
      report += `${i + 1}. ${file}\n`;
    });
  } else {
    report += 'No critical files identified.\n';
  }
  report += '\n';
  
  // Next Steps
  report += 'RECOMMENDED NEXT STEPS\n';
  report += '--------------------\n';
  if (results.roadmap.nextSteps.length > 0) {
    results.roadmap.nextSteps.forEach((step, i) => {
      report += `${i + 1}. ${step}\n`;
    });
  } else {
    report += 'No specific next steps recommended.\n';
  }
  report += '\n';
  
  // Production Readiness
  report += 'PRODUCTION READINESS\n';
  report += '------------------\n';
  report += `Score: ${results.roadmap.productionReadiness.score}/100\n`;
  
  if (results.roadmap.productionReadiness.issues.length > 0) {
    report += 'Issues:\n';
    results.roadmap.productionReadiness.issues.forEach(issue => {
      report += `- ${issue}\n`;
    });
  }
  
  if (results.roadmap.productionReadiness.recommendations.length > 0) {
    report += '\nRecommendations:\n';
    results.roadmap.productionReadiness.recommendations.forEach(rec => {
      report += `- ${rec}\n`;
    });
  }
  report += '\n';
  
  report += 'Generated by KNOUX Project Intelligence Desktop™\n';
  
  return report;
}

function exportJsonReport(results: AnalysisResult): string {
  return JSON.stringify(results, null, 2);
}

function exportHtmlReport(results: AnalysisResult): string {
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>KNOUX Project Intelligence Desktop™ - Analysis Report</title>
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
      background-color: #f8f9fa;
    }
    .header {
      background: linear-gradient(135deg, #6a11cb 0%, #2575fc 100%);
      color: white;
      padding: 30px;
      border-radius: 10px;
      text-align: center;
      margin-bottom: 30px;
      box-shadow: 0 4px 6px rgba(0,0,0,0.1);
    }
    h1 {
      margin: 0;
      font-size: 2.5em;
    }
    .summary-card {
      background: white;
      border-radius: 10px;
      padding: 20px;
      margin-bottom: 20px;
      box-shadow: 0 2px 10px rgba(0,0,0,0.05);
      border-left: 5px solid #6a11cb;
    }
    .progress-bar {
      height: 20px;
      background-color: #e9ecef;
      border-radius: 10px;
      overflow: hidden;
      margin: 10px 0;
    }
    .progress-fill {
      height: 100%;
      background: linear-gradient(90deg, #6a11cb, #2575fc);
      border-radius: 10px;
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      font-weight: bold;
    }
    .section {
      background: white;
      border-radius: 10px;
      padding: 25px;
      margin-bottom: 20px;
      box-shadow: 0 2px 10px rgba(0,0,0,0.05);
    }
    h2 {
      color: #6a11cb;
      border-bottom: 2px solid #eee;
      padding-bottom: 10px;
      margin-top: 0;
    }
    ul {
      padding-left: 20px;
    }
    li {
      margin-bottom: 8px;
    }
    .score-badge {
      display: inline-block;
      padding: 5px 15px;
      border-radius: 20px;
      font-weight: bold;
      margin-left: 10px;
    }
    .high-score {
      background-color: #d4edda;
      color: #155724;
    }
    .medium-score {
      background-color: #fff3cd;
      color: #856404;
    }
    .low-score {
      background-color: #f8d7da;
      color: #721c24;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>KNOUX Project Intelligence Desktop™</h1>
    <p>Advanced Project Analysis & Intelligence Report</p>
  </div>
  
  <div class="summary-card">
    <h2>Project Summary</h2>
    <p><strong>Name:</strong> ${results.projectSummary.name}</p>
    <p><strong>Type:</strong> ${results.projectSummary.type}</p>
    <p><strong>Size:</strong> ${formatFileSize(results.projectSummary.size)}</p>
    <p>
      <strong>Score:</strong> 
      <span class="score-badge ${
        results.projectSummary.score >= 80 ? 'high-score' : 
        results.projectSummary.score >= 50 ? 'medium-score' : 'low-score'
      }">${results.projectSummary.score}%</span>
    </p>
  </div>
  
  <div class="section">
    <h2>Technology Stack</h2>
    <p>${results.detectedStack.length > 0 ? results.detectedStack.join(', ') : 'None detected'}</p>
  </div>
  
  <div class="section">
    <h2>Progress Overview</h2>
    <p><strong>Overall Score:</strong> ${results.progressData.overallScore}%</p>
    
    <h3>File Status Distribution</h3>
    <div class="progress-bar">
      <div class="progress-fill" style="width: ${results.progressData.fileProgress.readyPercentage}%">
        ${Math.round(results.progressData.fileProgress.readyPercentage)}% Ready
      </div>
    </div>
    <p>
      Total: ${results.progressData.fileProgress.total} | 
      Ready: ${results.progressData.fileProgress.ready} | 
      Partial: ${results.progressData.fileProgress.partial} | 
      Stubs: ${results.progressData.fileProgress.stub}
    </p>
  </div>
  
  <div class="section">
    <h2>Critical Files</h2>
    ${results.roadmap.criticalFiles.length > 0 
      ? '<ul>' + results.roadmap.criticalFiles.map(file => `<li>${file}</li>`).join('') + '</ul>'
      : '<p>No critical files identified.</p>'
    }
  </div>
  
  <div class="section">
    <h2>Recommended Actions</h2>
    ${results.roadmap.nextSteps.length > 0 
      ? '<ul>' + results.roadmap.nextSteps.map(step => `<li>${step}</li>`).join('') + '</ul>'
      : '<p>No specific actions recommended.</p>'
    }
  </div>
  
  <div class="section">
    <h2>Production Readiness</h2>
    <p>
      <strong>Score:</strong> 
      <span class="score-badge ${
        results.roadmap.productionReadiness.score >= 80 ? 'high-score' : 
        results.roadmap.productionReadiness.score >= 50 ? 'medium-score' : 'low-score'
      }">${results.roadmap.productionReadiness.score}/100</span>
    </p>
    
    ${results.roadmap.productionReadiness.issues.length > 0 
      ? `
      <h3>Issues</h3>
      <ul>
        ${results.roadmap.productionReadiness.issues.map(issue => `<li>${issue}</li>`).join('')}
      </ul>
      `
      : ''
    }
    
    ${results.roadmap.productionReadiness.recommendations.length > 0 
      ? `
      <h3>Recommendations</h3>
      <ul>
        ${results.roadmap.productionReadiness.recommendations.map(rec => `<li>${rec}</li>`).join('')}
      </ul>
      `
      : ''
    }
  </div>
  
  <footer style="text-align: center; margin-top: 30px; color: #666;">
    <p>Generated by KNOUX Project Intelligence Desktop™</p>
  </footer>
</body>
</html>`;
}

function formatFileSize(bytes: number): string {
  if (bytes === 0) return '0 Bytes';
  
  const k = 1024;
  const sizes = ['Bytes', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}